version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/FreePIE.Console"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/FreePIE.Core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/FreePIE.GUI"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/FreePIE.GUI.CodeCompletion"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/FreePIE.Tests.Core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/FreePIE.Tests.Test"
    schedule:
      interval: "weekly"
